# Use jbossdemocentral/developer as the base
FROM jbossdemocentral/developer

# Maintainer details
MAINTAINER Andrew Block, Eric D. Schabell

# Environment Variables 
ENV DV_HOME /opt/jboss/bpms/jboss-dv-6.3
ENV DV_VERSION_MAJOR 6
ENV DV_VERSION_MINOR 3
ENV DV_VERSION_MICRO 0
ENV DV_VERSION_PATCH 1

ENV DV_INSTALLER=jboss-dv-$DV_VERSION_MAJOR.$DV_VERSION_MINOR.$DV_VERSION_MICRO-$DV_VERSION_PATCH-installer.jar

# ADD Installation and Management Files
COPY support/installation-dv support/installation-dv.variables installs/$DV_INSTALLER support/fix-permissions /opt/jboss/

# Update Permissions on Installers
USER root
RUN usermod -g root jboss && chown 1000:root /opt/jboss/$DV_INSTALLER

# Prepare and run installer and cleanup installation components
RUN sed -i "s:<installpath>.*</installpath>:<installpath>$DV_HOME</installpath>:" /opt/jboss/installation-dv \
    && java -jar /opt/jboss/$DV_INSTALLER /opt/jboss/installation-dv -variablefile /opt/jboss/installation-dv.variables \
    && /opt/jboss/fix-permissions $DV_HOME \
    && rm -rf /opt/jboss/$DV_INSTALLER /opt/jboss/installation-dv* $DV_HOME/standalone/configuration/standalone_xml_history/ 

# Copy demo and support files
COPY support/teiidfiles/data/* $DV_HOME/standalone/configuration/
COPY support/teiidfiles/standalone.xml $DV_HOME/standalone/configuration/
COPY support/teiidfiles/vdb/* $DV_HOME/standalone/deployments/
COPY support/teiidfiles/dashboard/* $BPMS_HOME/standalone/deployments/dashbuilder.war/WEB-INF/deployments/
COPY support/start-dv.sh /opt/jboss/

# Run Demo Maven build and cleanup
RUN chown -R 1000:root $DV_HOME \
  && /opt/jboss/fix-permissions $DV_HOME/standalone/configuration/standalone.xml \
  && /opt/jboss/fix-permissions $DV_HOME/standalone/configuration/flights-source-schema.sql \
  && /opt/jboss/fix-permissions $DV_HOME/standalone/configuration/hotels-source-schema.sql \
  && /opt/jboss/fix-permissions $DV_HOME/standalone/deployments/travel-vdb.xml \
  && /opt/jboss/fix-permissions $DV_HOME/standalone/deployments/travel-vdb.xml.dodeploy \
  && /opt/jboss/fix-permissions /etc/passwd \
  && /opt/jboss/fix-permissions /etc/group \
  && /opt/jboss/fix-permissions /opt/jboss/start-dv.sh \
  && chmod +x /opt/jboss/start-dv.sh 

# Run as JBoss 
USER 1000

# Expose Ports
EXPOSE 9990 9999 8080 31000 10090 10099 8180

# Default Command
CMD ["/bin/bash"]

# Helper script
ENTRYPOINT ["/opt/jboss/start-dv.sh"]
